name: Build Pyzbar for Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          set -e
          pip install --upgrade pip
          pip install pyzbar

      - name: Clone Mobile Forge
        run: |
          echo "Cloning mobile-forge repository..."
          git clone https://github.com/YasseenAlhusammi/mobile-forge.git
          cd mobile-forge
          echo "Running setup script for Android..."
          source ./setup-Android.sh || echo "Setup script for Android not found, manual setup may be required."

      - name: Install Mobile Forge
        run: |
          echo "Installing mobile-forge..."
          cd mobile-forge
          pip install -e .

      - name: Build Pyzbar for Android
        run: |
          cd mobile-forge
          echo "Building Pyzbar for Android..."
          forge android pyzbar

      - name: Locate the built wheel
        run: |
          ls dist
          if [ -z "$(ls -A dist)" ]; then
            echo "No wheels found in dist!"
            exit 1
          fi

      - name: Upload the wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyzbar-wheel
          path: dist/*.whl

      - name: Run tests
        run: |
          echo "Installing the built wheel..."
          pip install dist/*.whl
          echo "Running tests..."
          if python -m unittest discover -s tests; then
            echo "Tests passed!"
          else
            echo "Tests failed!"
            exit 1
          fi
