name: Build Pyzbar for Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found!"
          fi

      - name: Clone Mobile Forge
        run: |
          git clone https://github.com/YasseenAlhusammi/mobile-forge.git
          cd mobile-forge
          source ./setup-iOS.sh 3.11  # تأكد من أن السكربت موجود في المسار الصحيح

      - name: Build Pyzbar for Android
        run: |
          cd mobile-forge
          forge android pyzbar

      - name: Locate the built wheel
        run: |
          ls dist

      - name: Upload the wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyzbar-wheel
          path: dist/*.whl
