name: Build Pyzbar for Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          set -e  # اجعل السكربت يتوقف عند أي خطأ
          pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found!"
            exit 1
          fi

      - name: Clone Mobile Forge
        run: |
          git clone https://github.com/YasseenAlhusammi/mobile-forge.git
          cd mobile-forge
          source ./setup-iOS.sh 3.11  # تأكد من أن السكربت موجود في المسار الصحيح

      - name: Build Pyzbar for Android
        run: |
          cd mobile-forge
          forge android pyzbar

      - name: Locate the built wheel
        run: |
          ls dist
          if [ -z "$(ls -A dist)" ]; then
            echo "No wheels found in dist!"
            exit 1
          fi

      - name: Upload the wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyzbar-wheel
          path: dist/*.whl

      - name: Run tests
        run: |
          pip install dist/*.whl
          # استبدل test.py بمسار الاختبار الخاص بك
          if python -m unittest discover -s tests; then
            echo "Tests passed!"
          else
            echo "Tests failed!"
            exit 1
          fi
